### ISSUE TITLE
Avoid hacking the kie-server library

### ISSUE THREAD

**Issue by weimeilin79** [jbossdemocentral/brms-weightwatcher-realtime-decision-server-demo#14]
In the weight watcher rules, it is using the org.json.JSONObject library, which is not included in the kie-server library. Can you please change it Jackson library or something that is default included in the kie-server so We don't have to hack and copy the json-jar into the WEB-INF/lib ?

**Comment by DuncanDoyle** [comment]
The rules now use the default Jackson parser instead of JSON. JSON lib is no longer copied into the KIE-Server's lib directory. I also had to change the example request in "support/weightwatchers-query.xml", as Jackson did not allow some of the JSON strings in that request due to missing quotes around certain field names.
